# -*- coding: utf-8 -*-
"""P7DS_Descriptive Statistics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0j35gBYYULM6nWQF2ZoCD0an4zE73U0
"""

import pandas as pd

df=pd.read_csv('stats.csv')

df

"""Measure of Central Tendancy"""

# Mean Salary
mean1=df['Salary'].mean()
mean1

#Sum of Salaries
sum1=df['Salary'].sum()
sum1

#Maximum Salary
max1=df['Salary'].max()
max1

#Minimum Salary
min1=df['Salary'].min()
min1

#Total count

count1=df['Salary'].count()
count1

#Median
median=df['Salary'].median()
median

#Mode
mode1=df['Salary'].mode()
mode1

countrywise_sum=df.groupby(['Country'])['Salary'].sum()
countrywise_sum

countrywise_count=df.groupby(['Country']).count()
countrywise_count

"""Measure of variability"""

#variance of salaries
var1=df['Salary'].var()
var1

#standard deviation
std1=df['Salary'].std()
std1

"""Measure of Symmetry"""

skew1=df.skew(axis=0, skipna=True)
skew1

#The skewness is positive so x will have right side tail.

df.describe()